version: '3'

services:
  app:
    build: ./docker
    volumes:
      - ./docker:/var/www/html
    depends_on:
      - db
    ports:
      - 8000:8000
    tty: true

  db:
    image: mysql:5.7
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: password
